### ISSUE TITLE
Cauldron recipes non-functional

### ISSUE THREAD

**Issue by Gune02** [Sejoslaw/VanillaMagic#1]
The leather and gunpowder crafting works fine, but from the sugar achievement on out are just non-functional. Not sure if they have not been added yet.

**Comment by Sejoslaw** [comment]
Please check version 0.5.1.0 :)
For testing I use DebugMode (64x CommandBlock in both hands and right-click in air).
Thanks for Your help, I will check that normally now ;)

**Comment by Sejoslaw** [comment]
Fixed in 0.5.2.0 :)
