### ISSUE TITLE
Crash when Right Clicking w/ Portable Crafting Table

### ISSUE THREAD

**Issue by WenXin20** [Sejoslaw/VanillaMagic#12]
Forge 2026
Right Clicking with an empty hand crashed me. I also hand not unlocked portable crafting yet.
[Crash Report](http://pastebin.com/gwBXUncZ)

**Comment by Sejoslaw** [comment]
Yes I know I already fixed it and it will be fixed in the next version :)

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by Sejoslaw** [comment]
Check version 0.11.0.0
Tell me if there is everything fixed and I will close this issue :)

Btw thx for support ;)

**Comment by WenXin20** [comment]
Yes, and no problem. :)

**Comment by Sejoslaw** [comment]
Fixed in 0.11.0.0 :)
Closed.
