### ISSUE TITLE
Cauldron Crafting Not Working

### ISSUE THREAD

**Issue by WenXin20** [Sejoslaw/VanillaMagic#14]
I tried crafting the gunpowder, leather, cactus, and iron ore, but none seem to work. This was after I built the tear two alter and received the achievement for it.

**Comment by Sejoslaw** [comment]
Did You drop items into the Cauldron ?

**Comment by Sejoslaw** [comment]
You must craft 1 at a time.

**Comment by WenXin20** [comment]
Yes, and then right-clicked with the stick named Stick Wand

**Comment by Sejoslaw** [comment]
Try 1 at a time and than write if it works ;)

**Comment by WenXin20** [comment]
That's what I did, and it didn't work

**Comment by Sejoslaw** [comment]
Which version are You using ?

**Comment by WenXin20** [comment]
V0.11.1.2

**Comment by Sejoslaw** [comment]
Which version of Forge are You using ?

**Comment by WenXin20** [comment]
Forge v2050

**Comment by Sejoslaw** [comment]
It's strange because I don't see why it could not work..... :(

**Comment by WenXin20** [comment]
I just tried it with v0.12.0.0, but that didn't work either...

**Comment by Sejoslaw** [comment]
Ok tell me more. You didn't get the result item, that's what I know for now.
1 - You did the quest ?
2 - You have the right wand in right hand ?
3 - You dropped exactly the right amount of each item into Cauldron ?
4 - You build the Altar correctly ?

Try to tell me step-by-step what You did.
I know it may sounds stupid but it's really strange and I really want to know what didn't work :)
As for now.....I'm stupid :P

**Comment by WenXin20** [comment]
Ok, yes to all those
I had built there first tier for a while, back when the mod was version 0.8.0.1, before I upgraded to a tier 2 in v0.11.1.2. When the recipes didn't work, I broke everything and rebuilt it, but the crafting still didn't work. I think v0.8 was before the stick had to be named. After I built tier 2, I named the stick and got the first achievement again, but recipes still didn't work. I tried the coal and stick to make a fire and that worked, but none of the recipes for the cauldron seem to work.

**Comment by Sejoslaw** [comment]
Naming currently is unnecesarry. It will be implemented but since I'm not sure with the names for translations it's disactivated.
I will do more tests :P

**Comment by WenXin20** [comment]
Ok, thanks

**Comment by Sejoslaw** [comment]
Does it work now ? :)

**Comment by WenXin20** [comment]
Yes, although I am using a different world now.

**Comment by Sejoslaw** [comment]
Ok :)
So I will close this issue ;)
