### ISSUE TITLE
Adjust a few achievement positions

### ISSUE THREAD

**Issue by Mach12** [Sejoslaw/VanillaMagic#20]
Some achievement of the mod are too far away in the corners, and are not visible in certain conditions. Here I'd like to mention [Better Achievements](https://minecraft.curseforge.com/projects/betterachievements):

Better Achievements, while making the achievement screen look nicer, also restrains the visible area for achievements. Namely for this mod:
- You need to zoom out to see "Ore Doubling", "Craft 4x Coal Ore", "Craft Emerald Ore" and "Item Magnet" If those were just one [Whatever the position unit is] higher, it would be fine.
- "Summon spider" is only visible on maximum zooming level, and just barely. The other achievements beyond it are plain invisible.

So here it is. Try your mod with Better Achievements if you want to see for yourself.

(( Also there's a button on BA to switch to vanilla achievement viewer, but support for BA would be neat ))

**Comment by Sejoslaw** [comment]
I did checked the BetterAchievements. It look nicer but I can't see the problem with achievements position ? Yes it has some weird issues with showing achievements description but that's all. I can easily move the background to see all achievements.

**Comment by Mach12** [comment]
You can see the ones I listed?

Ok, I'll check on BA's side.

**Comment by Sejoslaw** [comment]
I did add the support for BA AchievementsPage icon.
