### ISSUE TITLE
Shift-right-clicking with an empty hand anything that is not recognized my the mod crashes your game

### ISSUE THREAD

**Issue by Mach12** [Sejoslaw/VanillaMagic#21]
Yeah. The title is pretty straightforward.

There are tons of reasons why this is dramatic. Mine is that I crash when I try to start a ritual from [Roots](https://minecraft.curseforge.com/projects/roots).

[Crashlog, yadda yadda...](https://github.com/Sejoslaw/VanillaMagic/files/435202/crash-2016-08-24_18.36.55-client.txt)

**Comment by WenXin20** [comment]
I got something similar, but when shift-right-clicking a lamp from actually additions.
[Crash Report](http://pastebin.com/nTqH5Ep5)

**Comment by Sejoslaw** [comment]
I will take a look on that :)

**Comment by Sejoslaw** [comment]
Could You please test version 0.13.1.0 and if everything is ok I will close the issue ? :)

**Comment by Mach12** [comment]
Sounds fixed to me!

I've yet to notice any side effect, but I confirm that I don't crash any more when I do the thing!

**Comment by Sejoslaw** [comment]
Ok so I will close this issue and if it happens again.....Just.....Write again :)
I hope not :P
Anyway Thank You for giving me crash reports. Thanks to that I noticed that You all had the same one issue ;)

Fixed in 0.13.1.0
