### ISSUE TITLE
Fix an abiguity in the "Capture Entity" achievement

### ISSUE THREAD

**Issue by Mach12** [Sejoslaw/VanillaMagic#22]
Said achievement is described as requiring a "Nether Wand".

I got confused by it because both the nether star and the blaze rod are Nether items, so they can both be called nether wands.

**Comment by Mach12** [comment]
Eh, did it myself.

If we were to give a special name to the Nether Star in the future, I suggest settling for something else than "Nether Wand".

**Comment by Sejoslaw** [comment]
Feel free to tell me the name :)
As I wrote on pull request Blaze Rod will be "Blaze Wand".

**Comment by Sejoslaw** [comment]
Changed it in 0.13.2.0.
I'm stupid :P
