### ISSUE TITLE
Should Acceleration Crystal use XP for each use ? (or something else)

### ISSUE THREAD

**Issue by Sejoslaw** [Sejoslaw/VanillaMagic#24]

**Comment by Mach12** [comment]
I don't think so. Your structure that accelerate things passively needs that kind of limitation (fuel like the quarry maybe?) but the crystal requires the player to keep the crystal in their main hand AND keep looking at the block. It's not much but I think having to draw all your attention to a single block you want to accelerate is kind of a big deal.
