### ISSUE TITLE
Support for Cave Biomes & Filled Ores Mod Redstone Ores

### ISSUE THREAD

**Issue by WenXin20** [Sejoslaw/VanillaMagic#25]
These mods ([Cave Biomes](https://minecraft.curseforge.com/projects/wtfs-expedition-cavebiomes-ores-trees-and-tweaks) & [Filled Ores](https://minecraft.curseforge.com/projects/filled-ores-packed-ores)) both adds redstone ore, and cave biomes replaces redstone ore with a this custom ore, so I am unable to get the redstone ore achievement.

**Comment by Sejoslaw** [comment]
Ok I will look on that ;)

**Comment by Sejoslaw** [comment]
Please check version 0.13.3.0 :)

**Comment by WenXin20** [comment]
Cool, thanks

**Comment by Sejoslaw** [comment]
Added in version 0.13.3.0

Closing ;)
