### ISSUE TITLE
Are Potioned Crystals too OP ?

### ISSUE THREAD

**Issue by Sejoslaw** [Sejoslaw/VanillaMagic#26]

**Comment by Mach12** [comment]
What are potioned crystals tho?

Is there a guide to this mod I'm missing? Because I usually guide myself through the mod using achievements, and there's no achievement for potioned crystals (whatever they are)

**Comment by Sejoslaw** [comment]
There is achievement called Potioned Crystal in the newest version :)
It's Nether Star with Potion combined in Cauldron and Nether Star gives Player constant power of that Postion.
