### ISSUE TITLE
Fix position of summoned mobs

### ISSUE THREAD

**Issue by Mach12** [Sejoslaw/VanillaMagic#27]
When you summon a mob with... well, a summoning spell, the mob is on the north-west corner of the block you aim for.

It's all fun and games until you right click a wall and the mob suffocates in it.

Obvious fix: add 0.5 X and Z to the position of the summoned thing.

**Comment by Sejoslaw** [comment]
Ups.
Please check version 0.15.0.2

**Comment by Mach12** [comment]
Does not seem fixed to me. Pig still spawned on the corner of this cobblestone.

![We're not quite there yet...](https://cloud.githubusercontent.com/assets/3253035/18163197/18f4ea48-703a-11e6-9ff8-15b01dab56df.png)

**Comment by Sejoslaw** [comment]
Hmm...It's strange because when I spawn Pig it stands like that:
![2016-09-01_13 44 22](https://cloud.githubusercontent.com/assets/13147684/18166264/6f3c61dc-704a-11e6-8774-96fc114be0b7.png)

**Comment by Sejoslaw** [comment]
Here is the code which handle spawning:
https://github.com/Sejoslaw/VanillaMagic/blob/master/VanillaMagic/src/main/java/seia/vanillamagic/quest/QuestCaptureEntity.java#L172
As You can see in the highlighted line, there is +0,5D on X and Z coordinates.

**Comment by Mach12** [comment]
LOL I get what you got wrong

If you look closely, you summoned it with the Capture spell, the one that is still broken is the _summon_ one!

I used porkchops in my secondary hand, see?

**Comment by Sejoslaw** [comment]
Hahahaha ok I will look deeper into that :D
Btw how did You use porkchop ? :D
Could You explain it to me ? :D

**Comment by Mach12** [comment]
Well I put a Nether Star in my right hand, 32+ raw porkchops in my left hand and right-clicked a block with this setup, and boom I get a pig where I click.

...was that not intended to happen? o_o

(oh yeah also I had to have the achievement available or unlocked for this to work, but that sounds normal to me since I use the achievements like a spellbook...)

**Comment by Sejoslaw** [comment]
Hahahaha ok I will look deeper into that :D
Btw how did You use porkchop ? :D
Could You explain it to me ? :D

**Comment by Sejoslaw** [comment]
Ouuu so You used Spawn Pig Quest okok i get it now.

**Comment by Sejoslaw** [comment]
Ok so I did add +0.5D on X and Z coordinate in Spell Summon Mob. It should work now.

**Comment by Sejoslaw** [comment]
https://github.com/Sejoslaw/VanillaMagic/commit/5496ed657617e97ae9444d9ee459420599127fe7

**Comment by Sejoslaw** [comment]
Please check version 0.15.0.4

**Comment by Mach12** [comment]
Aww yiss it works!!
