### ISSUE TITLE
cauldron don't brake

### ISSUE THREAD

**Issue by adoxentor** [Sejoslaw/VanillaMagic#32]
It just turns invisible

**Comment by Sejoslaw** [comment]
Could You describe me the problem ?

**Comment by adoxentor** [comment]
every time I try to break the cauldron it turns to a glitch block, invisible and glitchy when trying to move into. placing a different block in place of the "cauldron" the cauldron reappears.

**Comment by Sejoslaw** [comment]
Do You have all the achievements ?
Is the Cauldron a Quarry or any other VanillaMagic Tile ?
Did You use any spell on that block ?

**Comment by squirrelkiller** [comment]
I am having the same issue and by trying to use a block breaker to remove it I got this report off of a server:

http://pastebin.com/L8yCN15t

I did not set it up as a quarry nor do I have the required achievements.

EDIT: temp fix, use `/setblock ~ ~ ~ dirt` while standing inside of it to remove

**Comment by Sejoslaw** [comment]
Ok now I know why it was crashing. That was because of new events that I wrote specially for VM.
It tryed to start event on CustomTile when there was no CustomTile.
It should be fixed now.

Please try version 0.16.1.2
