### ISSUE TITLE
[1.10.2] Frustrating Quest Fixes Suggestions

### ISSUE THREAD

**Issue by squirrelkiller** [Sejoslaw/VanillaMagic#33]
So I remove these myself, but I feel they should either be removed or altered by default so they trigger properly for most players:

In the bottom branch:

"Craft Cauldron" and "Mine Redstone" both of these feel kinda superficial and tedious and overly hand holdy. Especially "Mine Redstone" which have lead to myself and others having to go out of their way to mine one piece of redstone to continue.

The entire Chunk Loader tree is just annoying.

Being lead down a tree in a specific order so as to get an enchanting table to build the construct is really just not fun, and once again overly hand holdy. It also leads to needing to go out of one's way to find diamond again as you are unlikely to have crafted a book, and especially not a bookshelf which is mainly used for enchanting, before getting diamonds.

My suggestion is either remove the entire tree or make them unordered but all required. Instead of a linear path, make "Build ChunkLoader" require "Craft Enchanting Table" which will require "Mine Diamond", "Mine Obsidian", and "Craft Bookshelf" but as 3 branches that combine into one branch again.

Same can be suggested for "Craft Cauldron" and "Mine Redstone". Make them both required, but not in a specific order.

**Comment by Sejoslaw** [comment]
First of all, Thank You for Your suggestion :)
Second of all, You can change them Yourself and just post a pull request OR put the code here OR on the pastebin.
I understand what You mean but now let's think about "clean look" of the quest tree. I mean the look and feel of all the quests positions and stuff like that.
If You remade the quests and they all works, I assume that You understand how to modify the JSON file and I must say "Good Job" :)

To add more required quests You must add the:
"additionalRequiredQuests":
{
    "quest_1":"pickBlazeRod"
}
It was taken from "Feel like Blaze" quest. But You can add more:
"additionalRequiredQuests":
{
    "quest_1":"pickBlazeRod",
    "quest_2":"UniqueQuestName2",
    "quest_3":"UniqueQuestName3",
    "quest_4":"UniqueQuestName4"
}

**Comment by Sejoslaw** [comment]
Please check version 0.16.2.0
