### ISSUE TITLE
Crash when starting the quarry

### ISSUE THREAD

**Issue by jonabrv1965** [Sejoslaw/VanillaMagic#34]
Hi. As soon as I put a coal block in the upper chest the game crashes. See log attached.

[crash-2016-09-18_09.46.28-server.txt](https://github.com/Sejoslaw/VanillaMagic/files/478779/crash-2016-09-18_09.46.28-server.txt)

**Comment by Sejoslaw** [comment]
Thanks :)
Please try version 0.16.2.1 :)
