### ISSUE TITLE
1.10.2-0.17.0.1 Initializing Crash

### ISSUE THREAD

**Issue by MisterShawn** [Sejoslaw/VanillaMagic#36]
[Crash Report](https://gist.github.com/sdaddy/91b49356a59387e009d732176e3e723b)

Forge: 12.18.1.2094

**Comment by Sejoslaw** [comment]
Please try version 0.17.0.2
Remember to delete Your config/VanillaMagic folder.

**Comment by MisterShawn** [comment]
Success! Thanks for the quick update.
