### ISSUE TITLE
Water Filtering?

### ISSUE THREAD

**Issue by HeroicConcept** [Sejoslaw/VanillaMagic#38]
Could you add a way to run water over a hopper with a crafting bench and chest (could add iron bars in the chest to act as a strainer) to pan out iron or gold nuggets and such?  Or is that something that'd be kind of silly to add?

**Comment by Sejoslaw** [comment]
Idea sounds funny but remember that Iron Nuggets doesn't exists in Vanilla Minecraft ;)
Your idea was to place an ore in chest and hopper will fill with nuggets from that ore ?

**Comment by HeroicConcept** [comment]
Ah I forgot about that with iron nuggets.  I was thinking of something more like a sieve system for resources that are vanilla from the water passing over the hopper.
