### ISSUE TITLE
[SERVER CRASH] 1.10.2-0.18.0.0 crashes dedicated Forge 1.10.2 build 2095 on startup

### ISSUE THREAD

**Issue by kreezxil** [Sejoslaw/VanillaMagic#39]
crash report:
https://gist.github.com/b3e9896e24df2a2ab3de908d23b2033e

fml server latest:
https://gist.github.com/2c6d1c3650fd17f2165313af675363e1

**Comment by kreezxil** [comment]
same error is reported with 1.10.2-0.17.0.2

crash report:
https://gist.github.com/0655e06358ccf1711495a7f88af06452

fml server latest:
https://gist.github.com/595f1b7b680a35a752a344d47b75025d

**Comment by kreezxil** [comment]
same again for 0.17.0.1

Issue:  vanilla magic 1.10.2-0.17.0.1 crashes dedicated Forge 1.10.2 build 2095 on startup

crash report:
https://gist.github.com/e6d3177c2626b602bebc721d910ffd42

fml server latest:
https://gist.github.com/2e637ee7c5031ded2445572eb732dd5f

**Comment by kreezxil** [comment]
I tested down to 0.17.0.0, 0.17.0.0 has no issue with starting on a dedicated server. :)

**Comment by Sejoslaw** [comment]
Try to delete config/VanillaMagic.
And rerun ;)

**Comment by kreezxil** [comment]
that solved it. since you require deleting that folder each time this upgraded, can you make it so that when the upgrade is detected that it deletes the folder automatically?

**Comment by Sejoslaw** [comment]
No. You can change the config by yourself if You know what You are doing. If I do autoremove and recopy, Your whole work would be ruined :-)

**Comment by Sejoslaw** [comment]
In theory You should only delete the config if I add a new Quest or move a Quest file to other directory.
But to make it clear I added information about deleting after each upgrade.

**Comment by Sejoslaw** [comment]
If fixed, I close the issue :-)
