### ISSUE TITLE
Should Quarry supports various Power APIs ??? (RF, EU, Tesla, Forge Energy, etc.)

### ISSUE THREAD

**Issue by Sejoslaw** [Sejoslaw/VanillaMagic#40]
I know it won't be "vanilla" but it will easy for someone who has power plant and don't want to place fuel in input chest.

**Comment by jonabrv1965** [comment]
uhm.. tough question my friend (very tempting a quarry powered by tesla/rf or whatever...). I must say ... no... What keep this mod apart and unique is precisely the "vanilla" touch, if you introduce any kind of third party energy to your contraptions it will be a some kind of weird mixture between magical and technological branches... thus there will be no more "vanilla" nor "magic"... IMHO... ;-)

**Comment by Sejoslaw** [comment]
Thank You for answer :-)
I thought about an Quarry Upgrade which could work like a battery or some kind of starage unit (for instance: redstone block in upgrade line).
How about some kind of VanillaMagic Addon or something like that ?
Additional mod which will add some optional things like that ?

**Comment by jonabrv1965** [comment]
Uhm... an addon!, this could be : mantain your original mod "vanilla" and "magic" (literally) and if anyone wants more can install the addon... makes sense..

About quarries using batteries... I've some experience with that and is not that efficient, you´ve to carry a bunch of batteries/capacitors/storage just to make a little quarry... I mean, it's ok, but better if the addon allows to connect to RF/Tesla and Forge Energy sources (I'm not sure that EU or MJs survive any further) as solar panels, windmills, etc....

Going further... what about to allow other kind of energy : Mana (Botania) and Vis (Thaumcraft)... 

The thing with an addon is that you have to create a new page in curse and all that hassle.... up to you!

**Comment by Sejoslaw** [comment]
I imagine Quarry with this Power Upgrade taking energy from any kind of source.
As output inventory You could place MEInterface or some kind of Ender Chest or the inventory which could teleport items somewhere.
I like Your arguments becouse they make sense and are more described than just "no" :-)
On the other hand I don't want to put effort into something that is more or less useless :-P

**Comment by jonabrv1965** [comment]
A word about usability : keep in mind that there are several other powered quarries in the MC environment (I particularly use the "builder" from RFTools, a very versatile and powerful machine) but I know several other (BC Quarry the precursor, EnderQuarry, several vertical miners, even a funny dinosaur that eats blocks like no tomorrow!! very funny and very expensive to get although not "powered")

Bottom line, there are several other options to automate mining, so you are entering in a competitive field that can undermine your effort. You have to determine if the effort is fruitful or not.

From my point of view Vanilla Magic breaks ground (and that´s why is  great mod) by its mechanics that put it apart of the rest and I love the "vanilla" feel and look. (just with vanilla blocks you can have a functional quarry, a functional chunkloader, a functional autocrafting system, etc.)

**Comment by Sejoslaw** [comment]
Ok I won't add it.
Thank You ;-)
