### ISSUE TITLE
Vanilla Quarry not working.

### ISSUE THREAD

**Issue by ravenlore** [Sejoslaw/VanillaMagic#41]
Using the newest version 0.20.0.0, running an instance with only Vanilla Magic and JEI installed with the latest forge version 12.18.2.2107. Tried in both creative & survival mode, with all achievement unlocked. Diamond block on the left, cauldron in the middle, right is chest, Redstone block at the back and on top is chest with fuel.
Right clicking with Blaze Wand on right hand with left hand empty. The quarry doesn't seems to work.

**Comment by Sejoslaw** [comment]
Thank You :-)
Please try 0.20.0.1
I don't have this problem so I'm not sure what is wrong but hopefully this will fix it.

**Comment by ravenlore** [comment]
Still not working for me. I've tried all the versions and it seems that it stopped working past version 0.19.0.0. In this version, it will say [VanillaMagic] TileQuarry Added. But on any other version from 0.19.1.0 to 0.20.0.1, nothing happens.

**Comment by Sejoslaw** [comment]
Try to delete config/VanillaMagic and tell me if it helps.

**Comment by ravenlore** [comment]
No, I had to keep deleting the config everytime I change the version, so that was not the problem.

**Comment by Sejoslaw** [comment]
Do You know how to open console in Minecraft ?
In profile settings You must change "close the launcher...." to "keep the launcher open" and the second page in launcher is called "Console" or something like that. It is something like logger.
If You try to place Quarry (right-click) it should give some information in console.
There are 3 possible informations Quarry: "Added", "Already exists", "Not Added".
Each VanillaMagic information will start with "[vanillamagic]".
Could You try to do it again and copy that information ?

**Comment by ravenlore** [comment]
Sorry, I only have my laptop atm so it took a while. Here is the log http://pastebin.com/U9QzxQLP

**Comment by ravenlore** [comment]
Thanks a lot, the quarry is working now.
