### ISSUE TITLE
Block absorber crash when there's a running liquid over the hopper.

### ISSUE THREAD

**Issue by ravenlore** [Sejoslaw/VanillaMagic#42]
Was trying to use the block absorber for a stone generator, while testing a water flow flowed on top of the hopper where the block is supposed to be absorbed and the game crashed. Here is the crash report: http://pastebin.com/zSp3euUZ

**Comment by Sejoslaw** [comment]
Thx :)
Please try 0.20.0.3
Close if the issue is fixed ;)

**Comment by ravenlore** [comment]
Yup, fixed, thanks again :)
