### ISSUE TITLE
I cant get the auto farmer and miner to work.

### ISSUE THREAD

**Issue by LocoMinerDad** [Sejoslaw/VanillaMagic#50]
I have the achievement for making it. I have added coal to the inventory chest, but nothing seems to be happening. What am I doing wrong?

Thank you

**Comment by Sejoslaw** [comment]
Do You have the information about the TileEntity being added ?

**Comment by LocoMinerDad** [comment]
What is a TileEntity?

**Comment by drutech** [comment]
Adding to this thread to learn. 

I can get the auto farmer together and I do get the TileFarm not TileEnety, but how dose it work? I have put it in the middle of a tilled earth at the base. I put tilled earth around the cauldron. Not sure how it works .

**Comment by Sejoslaw** [comment]
Cauldron should be 1 block higher than earth.
Container under cauldron should be on the same level as earth.
