### ISSUE TITLE
Crash on Minecraft Launch

### ISSUE THREAD

**Issue by TheElectricCake** [Sejoslaw/VanillaMagic#51]
[crash-2017-01-11_11.36.55-client.txt](https://github.com/Sejoslaw/VanillaMagic/files/699887/crash-2017-01-11_11.36.55-client.txt)

Modpack launches fine if I remove VanillaMagic. It might be a conflict but I'd appreciate your taking a look at it.

**Comment by Sejoslaw** [comment]
Delete Your config/VanillaMagic folder

**Comment by TheElectricCake** [comment]
Works, thank you very much!
