### ISSUE TITLE
[1.11.2] 0.21.1.6 excessive console spam

### ISSUE THREAD

**Issue by kreezxil** [Sejoslaw/VanillaMagic#52]
Aproximately every 30 seconds the mod does the following on the Dedicated Server console.

http://pastebin.com/884Uxv2i

**Comment by Sejoslaw** [comment]
VanillaMagic is saving Your CustomTileEntities (CTE). Something must force MC to save world.
MC saves world when You press Esc in singleplayer and once a while on multiplayer.
You have 6 worlds and something forces MC to save CTE on these worlds.
