### ISSUE TITLE
Server crash when ore mining obsidian

### ISSUE THREAD

**Issue by ProsperCraft** [Sejoslaw/VanillaMagic#53]
https://github.com/Funwayguy/OreExcavation/issues/32

**Comment by kreezxil** [comment]
it recurred again

http://paste.fedoraproject.org/538887/56422821/

**Comment by Sejoslaw** [comment]
Please check version 0.21.2.1 I did small crash-stop. If server crash, the crash-log will be shown in console.

**Comment by kreezxil** [comment]
Thank you I"ll be checking it soon.

**Comment by ProsperCraft** [comment]
Funway found the cause, see the link to his github 2 posts above.

**Comment by Sejoslaw** [comment]
Does it work now ?
