### ISSUE TITLE
Client crash when trying to upgrade pick in cauldron

### ISSUE THREAD

**Issue by DingoX3** [Sejoslaw/VanillaMagic#55]
I threw a diamond pick in the cauldron(tier 7 altar) with one piece of redstone dust then clicked cauldron with blaze wand and client crashes. Tried it a second time with just the diamond pick, same crash.

full crash report: http://pastebin.com/iDKAPf9D

Minecraft version 1.11.2
Forge version: 13.20.0.2226
Vanilla Magic version: 1.11.2-0.21.3.2
ModPack profile---> [One Elf Squared](https://mods.curse.com/modpacks/minecraft/256325-one-elf-squared)

**Comment by Sejoslaw** [comment]
It will be fixed in 0.21.4.0
