### ISSUE TITLE
[1.11.2] Vanilla magic moves portal blocks

### ISSUE THREAD

**Issue by ProsperCraft** [Sejoslaw/VanillaMagic#59]
verified on end portal the return portal the ender island portal  and nether portals

This is very bad on a multiplayer server, someone could remove the entire end portal.

Players can troll people with portal blocks, placing them so players hit them and get sent places.

Recommend- portal not able to be moved, or at the very least a config option to disable movement of portals.

**Comment by Sejoslaw** [comment]
Check version 0.21.7.0 and tell me if it works now ;)
