### ISSUE TITLE
[1.11.2-0.21.11.1] crashes dedicated server Forge 1.11.2 build 2260

### ISSUE THREAD

**Issue by kreezxil** [Sejoslaw/VanillaMagic#61]
Notes:
     on startup, it says invalid side SERVER, also I did delete the vanilla magic folder

crash report:
https://gist.github.com/91f06de1e8dd82dbe667f4a66026da47

fml server latest:
https://gist.github.com/c9590b07371ae2b25c5181a7d14a782e

**Comment by Sejoslaw** [comment]
Ok so it crashed because of the new command. I will disable it temporarily.

**Comment by Sejoslaw** [comment]
Please check the newest version :)
