### ISSUE TITLE
1.10.2 crash : IllegalArgumentException: Don't know how to convert minecraft:stone[variant=stone] back into data...

### ISSUE THREAD

**Issue by jonabrv1965** [Sejoslaw/VanillaMagic#63]
Happen when quarrying a big piece of terrain (using the builder from RFTools), the world became unusuable, every try to reload it give this crash.  I removed vanillamagic mod and was able to reload the world...

Here the crash log : 
[crash-2017-04-03_21.43.22-server.txt](https://github.com/Sejoslaw/VanillaMagic/files/892026/crash-2017-04-03_21.43.22-server.txt)

**Comment by Sejoslaw** [comment]
I'm not planning to update 1.10.2 in the near future, sorry :(

**Comment by jonabrv1965** [comment]
OOoopppsss!! Then removing from my pack. Thanks anyway for the fun time.

**Comment by Sejoslaw** [comment]
Thanks for finding issue ;)
It is already fixed in 1.11.2 :)
