### ISSUE TITLE
[1.11.2, 0.21.11.5]  couldn't get the first achievements of Vanilla Magic.

### ISSUE THREAD

**Issue by lomizandtyd** [Sejoslaw/VanillaMagic#64]
I got VM successfully loaded. 
But when I crafted a "Stick Wand", I didn't got the first achievement "Craft Stick" in VM.

I've tried ways below to solve it in offline game.
1. remove all mods and all configs, reinstall VM and create a new world.
2. use VM versions 0.21.11.3,  0.21.11.1..
3. rename stick with "Stick Wand", "stick wand".
4. change the language settings to "English US", I use "Simplified Chinese" as default.

Here is the log in my online server. [server log](https://pastebin.com/raw/Wi0FNran)

Both in single game or server, it seems VM has been loaded successfully....
I got six instruction books in my hand.

My forge version is 13.20.0.2228 in minecraft 1.11.2.

**Comment by Sejoslaw** [comment]
Currently Wand name is ignored. 
I'm using Forge 2282, try to update and tell me if it helps.

**Comment by lomizandtyd** [comment]
It doesn't help, sorry..

**Comment by Sejoslaw** [comment]
You should get achievement after crafting Stick. 
To be honest I have no idea why it doesn't work for You, sorry :(
I will try and do some tests to find it out.

**Comment by lomizandtyd** [comment]
@Sejoslaw ,        Thanks a lot for you.

I found a bypass solution in Cheat Mode by unlocking the first achievement.

1. open .minecraft/config/VanillaMagic/achievements.json
2. Change the questName of "Craft Stick" : "Craft Stick" -> "CraftStick"
3. return to the world, and type the command 
   `/achievement give CraftStick %USER%`
   change %USER% to your own username...
4. or `/achievement give *` for cheat.
5. Now works..

I didn't give a try in the achievement "Pick Blaze Rod".  
VM is a wonderful mod~ It's very nice of you to share the mod with everybody.
Reorganizing achievements as the original achievement identities maybe a good idea.
In the basic minecraft achievement system, all achievements get their own identity names.
Such as   `Taking Inventory` -> identity `achievement.takingInventory`

**Comment by Sejoslaw** [comment]
Thank You ^^

In VM is the same. If You open VanillaMagic-X.jar in program like WinRar You find inside a folder `assets/vanillamagic/lang/YourLanguageFile.lang` this files contains description of almost everything readable in VM, things like achievements and their descriptions, books names, etc.
