### ISSUE TITLE
Achievement IDs contain spaces, can't give them with the /achievement command

### ISSUE THREAD

**Issue by Mach12** [Sejoslaw/VanillaMagic#66]
The achievement comand expects achievements IDs to be a single word.
Therefore this assumes your achievement is named `Pick`:
    `/achievement give Pick Blaze Rod`
It isn't functional. Any of the following, however, would be very acceptable:
    `/achievement give PickBlazeRod`
    `/achievement give pickblazerod`
    `/achievement give pick_blaze_rod`
    `/achievement give pick-blaze-rod`
The best option is probably this;
    `/achievement give vanillamagic:pickblazerod`

Of course, same goes for all other achievements.

**Comment by Sejoslaw** [comment]
Please try the newest version of VanillaMagic.

**Comment by Mach12** [comment]
Tried it, new names makes the `achievement` command usable on this mod!

(Also props to you for adding the `vanillamagic:` prefix, a lot of modders neglect this)

**Comment by Sejoslaw** [comment]
Thx :)
Ok so this can be closed.
