### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Sejoslaw/VanillaMagic#77]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Vanilla Magic v2.0.1`

My server crashed during load.
[Crash Report](https://gist.github.com/WenXin20/ee65b6d234c5e7b1a5477488a785c5a7)

**Comment by Sejoslaw** [comment]
Please check v2.0.4
https://www.curseforge.com/minecraft/mc-mods/vanilla-magic/files/3074190

**Comment by WenXin20** [comment]
Thanks, but I am using v1.15.2 still. Will that be updated as well?

**Comment by Sejoslaw** [comment]
Sure thing.
Check this (under review currently)
https://www.curseforge.com/minecraft/mc-mods/vanilla-magic/files/3074225

**Comment by Sejoslaw** [comment]
Should be available now

**Comment by WenXin20** [comment]
Thanks!

**Comment by WenXin20** [comment]
Hello, I just tried v2.0.2 for 1.15, but got the same [server crash.](https://gist.github.com/WenXin20/4495fa11e0b5bc3520df0da2c79c136b)

**Comment by Sejoslaw** [comment]
Hard to say. It runs for me. I can suggest to try and generate new world with only Vanilla Magic (I've tried that and it worked fine).
If it happens without any other mods then we are in trouble; otherwise it may be some mod interactions errors.
I don't know what else to say for now :(

**Comment by WenXin20** [comment]
It might be a compat issue with the double slabs mod. The double slabs mod was crashing only when I had vanilla magic installed on the client, so maybe its crashing the server too.
CJMinecraft01/DoubleSlabs#141

**Comment by BenjaminLeSire** [comment]
Unfortunately, I can confirm it's still crashing. Only VanillaMagic, no other mod.
Minecraft 1.16.3, Forge 34.1.17, VanillaMagic 2.0.4.
Error is still: Vanilla Magic 2 (vanillamagic2) has failed to load correctly. java.lang.NoSuchFieldError: AIR
[Full crash report](https://hastebin.com/asenivuyum.txt)

**Comment by Sejoslaw** [comment]
I will check it with Forge 34.1.17
During dev I've used recommended which is 34.1.0

**Comment by Sejoslaw** [comment]
@BenjaminLeSire Please let me know if v2.0.5 fixes Your issue. I've changed wooden item tier quest to require stick item instead of an air.
https://www.curseforge.com/minecraft/mc-mods/vanilla-magic/files/3076787

**Comment by BenjaminLeSire** [comment]
No, it's the same error, except this time it's "java.lang.NoSuchFieldError: STICK". Very strange. It's as if there was no STICK field, but it's in the docs for net.minecraft.item.Items...

May I say though, you're impressively fast!

**Comment by Sejoslaw** [comment]
Hehe thanks but this error looks really weird.

**Comment by Sejoslaw** [comment]
I can see that You are using Forge client jar and Forge universal jar.
Could You please try with one one of them and let me know ?

**Comment by BenjaminLeSire** [comment]
I'm just using what ATLauncher sets up. Not sure I can remove one of them manually :/.

**Comment by BenjaminLeSire** [comment]
I tried with 34.1.0, same error. Then I tried with MultiMC, same error too. MultiMC also uses both forge-client and forge-universal, so I guess it's kinda how it must be?

**Comment by Sejoslaw** [comment]
Okok

**Comment by BenjaminLeSire** [comment]
Okay, ready for even stranger? I took your sources and built the mod for myself. Guess what? It works.

... I'm at a loss for what's happening.

**Comment by Sejoslaw** [comment]
Hahaha Now You have stick registered properly :D

**Comment by BenjaminLeSire** [comment]
I guess I can build it manually, but I still don't understand. Which OS are you building on? Do you just do gradlew build, or do you use something else?

**Comment by Sejoslaw** [comment]
Yeah Try it now please.
https://www.curseforge.com/minecraft/mc-mods/vanilla-magic/files/3076856
It is being processing right now.

**Comment by Sejoslaw** [comment]
Under Review.... Come on....

**Comment by Sejoslaw** [comment]
Should be available now

**Comment by BenjaminLeSire** [comment]
It's working!

**Comment by Sejoslaw** [comment]
Nice :)

**Comment by BenjaminLeSire** [comment]
I think you may have mistagged that file though: https://www.curseforge.com/minecraft/mc-mods/vanilla-magic/files/3076859
It's showing up for 1.16.3.

**Comment by Sejoslaw** [comment]
Yes, thank You ^^

**Comment by WenXin20** [comment]
I'm still getting a server crash with v2.0.3 though.
[Crash Report](https://gist.github.com/WenXin20/da0c38659cb7fbc42821b2a3ad5714f3)

**Comment by WenXin20** [comment]
> Sorry to say that but it's not telling me much what went wrong tbh.
It runs for me when I try and run it locally.
I mean the server.

I just know that it crashed when trying to run it on the server, I'm not sure what else I can give.
