### ISSUE TITLE
Problem with particles

### ISSUE THREAD

**Issue by BenjaminLeSire** [Sejoslaw/VanillaMagic#78]
VanillaMagic crashes the game when a mod using particles is added too.
That includes, but not limited to:

- ars-nouveau
- botania
- crossroads-mc
- elemental-craft
- mekanism
- mining-gadgets
- powah
- zycraft

[Here is a sample crash report, all of them look similar](https://pastebin.com/raw/bWAJzM6d)

**Comment by Sejoslaw** [comment]
Ok so I've tested it with ZYCraft and it runs smoothly together.

<img width="230" alt="Screenshot 2020-10-11 at 19 16 35" src="https://user-images.githubusercontent.com/13147684/95685148-61774980-0bf6-11eb-84e6-4cd4b7e56683.png">

<img width="275" alt="Screenshot 2020-10-11 at 19 16 40" src="https://user-images.githubusercontent.com/13147684/95685153-663bfd80-0bf6-11eb-9244-86ed8066e589.png">

**Comment by BenjaminLeSire** [comment]
Yes, I'm afraid the crash is a bit sneaky.

One, or sometimes two mods that add particles, can work fine. But add three and the crash will happen everytime.

I tried with mining-gadgets, immersive-engineering and zycraft. I can try other combinations for the same result. But remove Vanilla Magic and you can add as many mods with particles as you want, without crashing.

I'm really not sure the bug actually comes from Vanilla Magic, it may be a weird mod interaction, but somehow, without Vanilla Magic, the other mods manage to play well enough together.

[Crash report](https://hastebin.com/ezagedoxow.txt)

**Comment by Sejoslaw** [comment]
Yes, but the thing is that Vanilla Magic does not add any new particles.
It only adds 2 new Screens which are Quest GUI and VM Tile Entity Details GUI.
I really would love to fix that if I only knew what in Vanilla Magic is causing it hehe

**Comment by Sejoslaw** [comment]
Ok so I've tested it with Mining Gadgets as well and it worked.... ehh.....
The only difference is that various mods use different MCP mapping versions O.o
Maybe that's the reason ?

**Comment by BenjaminLeSire** [comment]
Correct, adding just mining-gadgets doesn't crash. But it is as I say, sometimes two mods adding particles are fine. Now try adding any third mod, for example immersive-engineering as I did, I bet you will have the same crash as I do.

**Comment by Sejoslaw** [comment]
Could You please try with the newest version and let me know if it works ?

**Comment by BenjaminLeSire** [comment]
I just checked, it works.
So I traced back the commits to find what fixed it, and it was e01deda5. Nothing to do with particles though, weird. But I know next to nothing about modding, so who am I to say. Thanks!

**Comment by Sejoslaw** [comment]
Thank You.
Can we close the issue ?
Sounds like it works how it should ?

**Comment by BenjaminLeSire** [comment]
Yes. There are other issues, but unrelated.
