### ISSUE TITLE
Crash w/ Wyrmroost & Nethercraft

### ISSUE THREAD

**Issue by WenXin20** [Sejoslaw/VanillaMagic#79]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Vanilla Magic v2.0.3`
[`Wyrmroost v1.2.2`](https://www.curseforge.com/minecraft/mc-mods/wyrmroost)
[`Nethercraft v1.0.9`](https://www.curseforge.com/minecraft/mc-mods/nethercraft-classic)

The game crashes on load after adding vanilla magic. The logs mention both Wyrmroost & Nethercraft, neither of which had crash before adding vanilla magic.
[Crash Log](https://gist.github.com/WenXin20/1fb9755d44a3b211a6d6f4bd4b63e27a)

**Comment by Sejoslaw** [comment]
Please give it a try after it will be reviewed and available for public.
https://www.curseforge.com/minecraft/mc-mods/vanilla-magic/files/3077009

**Comment by WenXin20** [comment]
Alright, thanks!

**Comment by WenXin20** [comment]
Neither the server nor the client crashed with the latest release, but the client log was spammed with an error and it also causes an error when trying to join the server.
[Log](https://gist.github.com/WenXin20/5cc45a938ab4f46dd88987bec1a3ae09)
[Server Log](https://gist.github.com/WenXin20/000fe5c652c8dfe89939591bfa3f736e)

**Comment by Sejoslaw** [comment]
I've added checking if there are any Quests registered for a specified "caller" so it should allow You to join correctly.
Also I've simplified the check for TileEntity in VMTIleInventoryBridge so it shouldn't throw that many errors.
https://www.curseforge.com/minecraft/mc-mods/vanilla-magic/files/3077440
Please let me know if it works for You now :)

**Comment by WenXin20** [comment]
Thanks! I'll see if I can give it another try tomorrow.

**Comment by WenXin20** [comment]
It is no longer crashing on load,  but I did get a different crash with the menu. I'll make a new report for that.
