### ISSUE TITLE
Quest Menu Crash

### ISSUE THREAD

**Issue by WenXin20** [Sejoslaw/VanillaMagic#80]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Vanilla Magic v2.0.5`

After pressing `o` to view the Quest Menu, my game crashed client-side while on my server.
[Crash Report](https://gist.github.com/WenXin20/90de7c5db0eebc597de263546f3710a7)

**Comment by Sejoslaw** [comment]
I wonder... Do You have "VanillaMagicQuests.json" file in "config" directory on Your server and client ?

**Comment by WenXin20** [comment]
The file is there, but it is an empty/blank file.
Will deleting the file fix that?

**Comment by WenXin20** [comment]
I tried deleting it, but the new file is also blank.

**Comment by Sejoslaw** [comment]
This is weird....
You could try and copy it from Your client config's directory.
It should be a JSON file with around 2,4k lines.

**Comment by Sejoslaw** [comment]
It contains all of the definitions of available Quests (feel free to modify it hehe)

**Comment by WenXin20** [comment]
The client's json file is also blank. Deleting it didn't fix it either.

**Comment by Sejoslaw** [comment]
Ok I'll check that. Thanks.

**Comment by WenXin20** [comment]
I'm getting an error in the log still. It looks like this is why the json file is blank.
https://gist.github.com/WenXin20/88dc77cbde52bf1ab04df04a37083f97

**Comment by Sejoslaw** [comment]
Yeah, probably the paths are different.

**Comment by Sejoslaw** [comment]
Here is how the file should look like:
https://github.com/Sejoslaw/VanillaMagic/blob/2.X-1.16.3-forge/src/main/resources/VanillaMagicQuests.json

**Comment by Sejoslaw** [comment]
Feel free to download it for now

**Comment by WenXin20** [comment]
Alright, thanks

**Comment by Sejoslaw** [comment]
Sorry for not testing it too much.

**Comment by Sejoslaw** [comment]
This should fix the issue (I hope):
https://www.curseforge.com/minecraft/mc-mods/vanilla-magic/files/3078294
Please give it a try when it will be Available

**Comment by WenXin20** [comment]
No worries! I'll see if I can give it a try tomorrow.

**Comment by WenXin20** [comment]
The menu is not crashing anymore :)
How do I complete quests? I crafted a stick, but the quest did not complete.
Also, if I soon out too far, all the quests display in one spot, and then if I zoom out again, all the quests switch the spot they are at.

**Comment by Sejoslaw** [comment]
Yeah. About the zooming I know. I felt like it was a cool feature to make it mirrored hehe
Well, You should be able to complete them by crafting a stick.
Are You playing on server ?

**Comment by WenXin20** [comment]
Oh, cool, I was wondering about that.
Yep, I'm on a server, but crafting the stick didn't complete it.

**Comment by Sejoslaw** [comment]
I'm checking that right now.
You probably received a message but nothing happened.

**Comment by WenXin20** [comment]
Yeah, I got a message, put nothing happened
By the way, the quest "Summon Lama" is misspelled. In Minecraft, Llama is spelled with two L's in it.

**Comment by Sejoslaw** [comment]
Thanks ^^

**Comment by Sejoslaw** [comment]
Could You please give it a try ?
https://www.curseforge.com/minecraft/mc-mods/vanilla-magic/files/3080121
This should fix the Quests sync issues.

**Comment by WenXin20** [comment]
Sure!

**Comment by WenXin20** [comment]
It's working now, thanks for the help. :)
