### ISSUE TITLE
Stick Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Sejoslaw/VanillaMagic#81]
`Minecraft v1.15.2`
`Forge v31.2.45`
`Vanilla Magic v2.0.6`

My server crashed after right-clicking a stick on a grass block.
[Crash Report](https://gist.github.com/WenXin20/8eefcaee5a2a8c34813eb2cf2dd3c9b0)

**Comment by WenXin20** [comment]
Looks like the crash is actually happening if I right-click with any block or item.

**Comment by Sejoslaw** [comment]
Please try 2.0.7

**Comment by WenXin20** [comment]
Looks to be fixed :)
