### ISSUE TITLE
Unstackble inventory bug

### ISSUE THREAD

**Issue by Lucksinia** [Sejoslaw/VanillaMagic#82]
Found an interesting bug(or it's a feature).

When pickup Any type of item in minecraft, they don't stack, and player need to stack'em up manually
![image](https://user-images.githubusercontent.com/63837173/96349141-4c972c00-10b6-11eb-94bb-9ca1bceec87c.png)

**Comment by Sejoslaw** [comment]
I'm checking that :)

**Comment by Sejoslaw** [comment]
Please try
https://www.curseforge.com/minecraft/mc-mods/vanilla-magic/files/3086429
If it will work please close the issue :)
Thanks ^^

**Comment by Sejoslaw** [comment]
Fixed

**Comment by WenXin20** [comment]
Thanks for the bug fix! I could not figure out what was causing it, which was pretty frustrating. Glad I saw this!

**Comment by Sejoslaw** [comment]
There were 2 places where NBT tags of items were checked. And I was creating new Tag for item if none existed. It was causing it. I had to change it to first check if Tag exists and if so check the value I needed.

**Comment by PorroxD** [comment]
Hi, I have the exact same problem. First I had version 1.16.3-2.0.15, after the problem I changed to 2.0.14, and it remained the same.
Also, removing the mod crashes the game.

**Comment by Sejoslaw** [comment]
You should (if possible) drop / remove blocks and items which You've picked up during the time You had old version installed.

**Comment by PorroxD** [comment]
Hello, I updated to version 2.0.17 and the problem continues. I deleted the config file and nothing. I created another world and it's still the same.
Then I emptied ALL of my inventory, deleted the config file again and it still crashes my world when I try to load it.
I will have to create another world (again) without the mod.
NOTE: It appears that the Tag change interferes with villager raising. I'll check it out in the new world without the mod. I'll tell you later.

Sorry for my english.

**Comment by Sejoslaw** [comment]
Can You try generate new world having only Vanilla Magic mod installed please ?
I've tested it and it works on my side.
I'm thinking about if it may interfere with any other mod that You're using (maybe).
Please let me know if You try.

**Comment by PorroxD** [comment]
Hello, first I created a new world only with Vanilla Magic 2.0.18, Optifine, JEI, JER, Hwyla and Wawla, and continues the problem, even crash the game when I try to open the Quest GUI. Then, I created a new world with Vanilla Magic and Optifine, nothing. And finally, I created a new world only with Vanilla Magic and the bug continues, and if I try to open the Quest GUI the game crashes.
I repeat, sorry for my English.

**Comment by Sejoslaw** [comment]
I will try and investigate it deeper.
Thanks.
For now I'm not sure what can cause that.

**Comment by PorroxD** [comment]
Okay, I'm waiting. And anything that I can help you tell me

**Comment by Sejoslaw** [comment]
I will, thanks.
One more question. About that Quest GUI crash.
Could you check if you have VanillaMagicQuests.json file in config directory, please ?
If so, is it filled with data ?

**Comment by PorroxD** [comment]
Yes it is, and yes, it has data
